# Generated by Django 5.0.2 on 2024-02-27 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cc", models.TextField()),
                ("pi", models.TextField()),
                ("pmh", models.TextField()),
                ("drugs", models.TextField()),
                ("sh", models.TextField()),
                ("fh", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female"), ("O", "other")],
                        max_length=6,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("PO", "مطب"),
                            ("CL", "درمانگاه"),
                            ("EMS", "اورژانس"),
                            ("ROT", "بخش"),
                        ],
                        max_length=3,
                    ),
                ),
                ("job", models.CharField(blank=True, max_length=20, null=True)),
                ("dwelling", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "age",
                    models.PositiveSmallIntegerField(verbose_name={"max_value": 150}),
                ),
                ("doctor", models.CharField(blank=True, max_length=20, null=True)),
                ("source", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "reliability",
                    models.CharField(
                        blank=True,
                        choices=[(1, "1/3"), (2, "2/3"), (3, "3/3")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("setting", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "PR",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name={"max_value": 600}
                    ),
                ),
                (
                    "BP_S",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name={"max_value": 250}
                    ),
                ),
                (
                    "BP_D",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name={"max_value": 250}
                    ),
                ),
                (
                    "RR",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name={"max_value": 60}
                    ),
                ),
                (
                    "SPO2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name={"max_value": 100}
                    ),
                ),
                (
                    "Temp",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name={"max_value": 45, "min_value": 30},
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=40)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
