# Generated by Django 5.0.2 on 2024-02-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hx",
        ),
        migrations.DeleteModel(
            name="Info",
        ),
        migrations.DeleteModel(
            name="VitalSigns",
        ),
        migrations.AddField(
            model_name="case",
            name="BP_D",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name={"max_value": 250}
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="BP_S",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name={"max_value": 250}
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="PR",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name={"max_value": 600}
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="RR",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name={"max_value": 60}
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="SPO2",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name={"max_value": 100}
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="Temp",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name={"max_value": 45, "min_value": 30}
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="age",
            field=models.PositiveSmallIntegerField(
                default=40, verbose_name={"max_value": 150}
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="cc",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="doctor",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="drugs",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="dwelling",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="fh",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="gender",
            field=models.CharField(
                choices=[("M", "male"), ("F", "female"), ("O", "other")],
                default="O",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="job",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="location",
            field=models.CharField(
                choices=[
                    ("PO", "مطب"),
                    ("CL", "درمانگاه"),
                    ("EMS", "اورژانس"),
                    ("ROT", "بخش"),
                ],
                default="ROT",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="pi",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="pmh",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="pretext",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="reliability",
            field=models.CharField(
                blank=True,
                choices=[(1, "1/3"), (2, "2/3"), (3, "3/3")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="setting",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="sh",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="source",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
