# Generated by Django 5.0.2 on 2024-02-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_delete_hx_delete_info_delete_vitalsigns_case_bp_d_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="BP_D",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="BP_S",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="PR",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="RR",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="SPO2",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="Temp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=2, null=True
            ),
        ),
    ]
