# Generated by Django 5.0.2 on 2024-02-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0003_alter_case_bp_d_alter_case_bp_s_alter_case_pr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="SPO2",
        ),
        migrations.AddField(
            model_name="case",
            name="SPO2_N",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=95, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="SPO2_O",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=95, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="date_of_admission",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="is_married",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "متاهل"),
                    ("s", "مجرد"),
                    ("w", "همسر فوت شده"),
                    ("d", "مطلق/مطلقه"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="BP_D",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=80, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="BP_S",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=120, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="PR",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=70, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="RR",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=18, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="Temp",
            field=models.DecimalField(
                blank=True, decimal_places=0, default=37, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="age",
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name="case",
            name="drugs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="fh",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="pmh",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="reliability",
            field=models.CharField(
                blank=True,
                choices=[(5, "5/5"), (4, "4/5"), (3, "3/5"), (2, "2/5"), (1, "1/5")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="sh",
            field=models.TextField(blank=True, null=True),
        ),
    ]
