# Generated by Django 5.0.2 on 2024-02-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0004_remove_case_spo2_case_spo2_n_case_spo2_o_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="is_married",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "متاهل"),
                    ("s", "مجرد"),
                    ("w", "همسر فوت شده"),
                    ("d", "جداشده"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="reliability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5", "5/5"),
                    ("4", "4/5"),
                    ("3", "3/5"),
                    ("2", "2/5"),
                    ("1", "1/5"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
