# Generated by Django 5.0.2 on 2024-02-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0005_alter_case_is_married_alter_case_reliability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="SPO2_N",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="SPO2_O",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=3, null=True
            ),
        ),
    ]
