# Generated by Django 5.0.2 on 2024-02-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0006_alter_case_spo2_n_alter_case_spo2_o"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="cc",
            field=models.CharField(default="", max_length=100),
        ),
    ]
