# Generated by Django 5.0.2 on 2024-02-27 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0007_alter_case_cc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="is_married",
            new_name="marriage",
        ),
    ]
