# Generated by Django 5.0.2 on 2024-02-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0009_alter_case_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="pdx",
            field=models.TextField(blank=True, null=True, verbose_name="Primary Dx"),
        ),
        migrations.AddField(
            model_name="case",
            name="phe",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
