# Generated by Django 5.0.2 on 2024-02-27 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0010_case_pdx_case_phe_case_summary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="drugs",
        ),
        migrations.AddField(
            model_name="case",
            name="act",
            field=models.TextField(blank=True, null=True, verbose_name="Actions"),
        ),
        migrations.AddField(
            model_name="case",
            name="alg",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Allergies"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="dat",
            field=models.TextField(
                blank=True,
                help_text="Including Previous Lab Data and Images and ECGs.",
                null=True,
                verbose_name="Other Data",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="drg",
            field=models.TextField(
                blank=True, null=True, verbose_name="Drugs and Addictions"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="BP_D",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=80,
                max_digits=3,
                null=True,
                verbose_name="Diastolic BP",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="BP_S",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=120,
                max_digits=3,
                null=True,
                verbose_name="Systolic BP",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="SPO2_N",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=3,
                null=True,
                verbose_name="SPO2 Without Oxygen",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="SPO2_O",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=3,
                null=True,
                verbose_name="SPO2 With Oxygen",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="Temp",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=37,
                max_digits=2,
                null=True,
                verbose_name="Temperature",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="cc",
            field=models.CharField(
                default="", max_length=100, verbose_name="Cheif Complaint"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="fh",
            field=models.TextField(
                blank=True, null=True, verbose_name="Family History"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="pdx",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Primary Dx"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="phe",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Physical Examinations and Review of Systems",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="pi",
            field=models.TextField(default="", verbose_name="Present Illness"),
        ),
        migrations.AlterField(
            model_name="case",
            name="pmh",
            field=models.TextField(
                blank=True, null=True, verbose_name="Past Medical History"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="sh",
            field=models.TextField(
                blank=True, null=True, verbose_name="Social History"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.case"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=2,
                        verbose_name="Days After Admission",
                    ),
                ),
                ("text", models.TextField(default="", verbose_name="Note")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.case"
                    ),
                ),
            ],
        ),
    ]
