# Generated by Django 5.0.2 on 2024-02-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0012_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="date_of_admission",
        ),
        migrations.AlterField(
            model_name="case",
            name="dat",
            field=models.TextField(
                blank=True,
                help_text="Including Previous Lab Data and Images and ECGs.",
                null=True,
                verbose_name="Paraclinic Data",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="gender",
            field=models.CharField(
                choices=[("آقا", "Male"), ("خانم", "Female"), ("دیگر", "Other")],
                default="O",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="location",
            field=models.CharField(
                choices=[
                    ("مطب", "مطب"),
                    ("درمانگاه", "درمانگاه"),
                    ("اورژانس", "اورژانس"),
                    ("بخش", "بخش"),
                ],
                default="ROT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="marriage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("متاهل", "متاهل"),
                    ("مجرد", "مجرد"),
                    ("همسر فوت شده", "همسر فوت شده"),
                    ("جداشده", "جداشده"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="slug",
            field=models.SlugField(
                help_text="لینک مورد علاقه برای کیس خود را وارد کنید. تلاش کنید لینکتان گویا و دقیق باشد، پس از این توانایی تغییر آن را نخواهید داشت.",
                max_length=40,
                unique=True,
                verbose_name="Link",
            ),
        ),
    ]
