# Generated by Django 5.0.2 on 2024-03-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0014_case_verified_alter_case_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="followup",
            name="date",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=2,
                verbose_name="Days After Admission:",
            ),
        ),
        migrations.AlterField(
            model_name="followup",
            name="text",
            field=models.TextField(
                help_text="توجه کنید که نت\u200cها در حال حاضر، قابل تغییر یا پاکسازی نیستند.",
                verbose_name="Note",
            ),
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
