# Generated by Django 5.0.2 on 2024-03-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0015_comment_verified_alter_followup_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="cat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ریه", "ریه"),
                    ("هماتولوژی و انکولوژی", "هماتولوژی و انکولوژی"),
                    ("روماتولوژی", "روماتولوژی"),
                    ("غدد", "غدد"),
                    ("گوارش", "گوارش"),
                    ("نفرولوژی", "نفرولوژی"),
                    ("جنرال", "جنرال"),
                    ("قلب", "قلب"),
                    ("پوست", "پوست"),
                    ("اطفال", "اطفال"),
                    ("زنان", "زنان"),
                    ("اعصاب", "اعصاب"),
                    ("روان", "روان"),
                    ("ENT", "ENT"),
                    ("عفونی", "عفونی"),
                    ("چشم", "چشم"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
