# Generated by Django 5.0.2 on 2024-03-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0017_alter_case_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="cat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ریه", "ریه"),
                    ("هماتولوژی و انکولوژی", "هماتولوژی و انکولوژی"),
                    ("روماتولوژی", "روماتولوژی"),
                    ("غدد", "غدد"),
                    ("گوارش", "گوارش"),
                    ("نفرولوژی", "نفرولوژی"),
                    ("جنرال", "جنرال"),
                    ("قلب", "قلب"),
                    ("پوست", "پوست"),
                    ("اطفال", "اطفال"),
                    ("زنان", "زنان"),
                    ("اعصاب", "اعصاب"),
                    ("روان", "روان"),
                    ("ENT", "ENT"),
                    ("عفونی", "عفونی"),
                    ("چشم", "چشم"),
                    ("مسمومین", "مسمومین"),
                ],
                max_length=100,
                null=True,
                verbose_name="دسته:",
            ),
        ),
    ]
