# Generated by Django 5.0.2 on 2024-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BS", "Basic Sciences"),
                    ("PP", "Physiopathology"),
                    ("EX", "Medical Extern"),
                    ("IN", "Medical Intern"),
                    ("GP", "General Practicioner"),
                    ("RS", "Medical Resident"),
                    ("SP", "Medical Specialist"),
                    ("FL", "Fellowship"),
                    ("SS", "Superspecialist"),
                    ("--", "-None-"),
                ],
                help_text="Your current degree.",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="university",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MUMS", "علوم پزشکی مشهد"),
                    ("TUMS", "علوم پزشکی تهران"),
                    ("----", "-None-"),
                ],
                help_text="Your current university.",
                max_length=4,
                null=True,
            ),
        ),
    ]
